language: node_js
node_js:
  - "node"
services:
  - postgresql
env:
  global:
    - PGPORT=5432
    - DB_NAME=chitter_test
    - DB_USER=trevor
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"