language: node_js
node_js:
  - "node"
services:
  - postgresql
env:
  global:
    - PGPORT=5432
    - DB_NAME=chitter_test
    - DB_USER=trevor
    - secure: "10j2RVCBo60FCv3SKRtF8xA6dRxDlwL4UMbrjETGEjHEY76FgNpPhRz+mtqmXN/u+rkjlZIa6ySsxZVpXMDzifNQUuS4iDf7wTMEHF5CJciNWRuWYxnU957KJ+SFUbUXVemVTLNg1rVkaUikZY9ymbrJvuopbsgUEIsS96+deGn4uC8rA+r2Hc9wXZCiq/P17iTRuaDUUxk8N+9pe1Wto2WKBM33tZyiFFUFNaXRNYJgBvo74xWM0GNGr751XXMcwCc2HgKWPAk8fyq5AcXl+GT4W0Xp+lZTRlnRL3Zyp1fwdCHKJaYPVD4iuvtVij1mY2qtHYQ2/81x2rTgm6iydUUTLZ84OCnb0d3hAI6J+T0ALQpL6ms5KPh+M8zwW2ZnClDRgKAeWbqYYXbeqDQGObkWi+OJznVZrzhJ6kxERtX/VKFyn1hbLBna/LBuJmV8A5yCwYOfCNNQ2QLGAAFVxCCOWYAdwMPli8ry1rHQ/iw5LB4MpOG3ZG0oqpg/FIFqFOCWvYP7LtS3b3x8wAm+6pkO7daNPutZBJfhxxBoXjyN4788OVntx47x/tOkPBU+1rw33ybC79hVFDM8AfFM4SQ9BcSfcdlmQQDU7CLXKuFW9BXGAzui7lOru27EoVmRhuCjKEQNg6DT3RNajbCVbGJdBXippNYrNS/B7c7gcG0="
    - secure: "U6DUdNFkJzi79XdYvohMHicz6xolZPN1OBDvDm4NeSp5TPgO1+GR3OJIkNlQVJYaTb8HEp90YBeONf/IC8XWIukfK9ndkNvTB7chsO6mjypQgw/IQQhhpr46XUQ7gfPqaawAa+ETrhYj/4AH5yENjLuTtxkgP4moXlfBqwXC6pM+NgKuivVfhe950tK6RII8qSbQrhLHXCB/OqE/VgKTx4XvonIXvOXO1DF36csCnqZ9KK6MXkpTAwg35XP99XToRn08h3z5mbvAb0eceGNAlrjNurSdKLc00VMR/PbFGYyNlAs5CyUYD57YNF6rsNqoO0ZHuWERlmdxplvPruq99fFUmIc1UK4SGotob9M59etfKEzmCjgcv+u7SXBbhK68jKTw++ui+IQK/8BQEcvQ9Wjqsi8JNOVji/MH/nzl+7zc0qk6S54izYfKxwmQtdTVF/V/7XvBFn5yPVO2ddqQxehu9Zw3EzSAe04+0eNsT4uniRv/DSEjy8E51018hPkKraZC47uKzgLmcdVQP38dz+IulY9ZJAX/fzsL2l/iJnIH/+05W2OUNFfdkjwL4mp/expjaUT1eRf5CA/dRCq+ArH0/PUKFdheUiA7WZsVnXOKwNLrglQ+HpF6gsgxL/Useh9+YSN9Jt0DBYAxuFmY8dApuNC7guDvO86PjI4+nSA="
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"